apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: votingbooth-prod
spec:
  encryptedData:
    redis-password: AgBH3QOQvl3isw/vcLiKOsyrvPT25mVEggQ7aawex2VqEbpjYIZw+qk83xjK+XfE23vTxBSgYtlKs2KJk2TlOfQHwh44tIroVudbye7vxTsMy2MwSHn0RPL2ogzYEYTU4NmN7wUF3djD2gx9DUYQiSsfsh58qKSzm8BJdb0UiglD9EesVZlZFcGSR2/6cxlEd1HfLUe4vtNky3VYE37dN0NkZjKzKu3tgW+iXIhed/+u18KhYeObpu1cA40VqmwB0piQgMvr55AGYkf5586Ev5dXr6/TQhz5lgnoJ78FTxX9czV+Ti57Iu+vM4unrwpf0gUWtiw1OgovjmZAYwHl+OPkisHTT1JtLsm7gQXmiobZ25b6DRLzG+AzVz/cjVo9lH6z+YM5KMbOBfftN4pHUllRRRhw3W3E4jqUrky6CbJm61tu+jRzFXeBVRk4OPVeD0vJ0b4/whYjrgDC0w1PQ4TKgjPp0EkZv2BXFcHW3mrIcNyvFN4QN/0MHjUqJSY+h7k+QJ4VxFVCN7N33TRmc+5g4hB92JifN+GBcWDyDAmqroxVJPqwBgMjldIMg8h3e/P6nZoc8g0HW45S7+5ObtwOYYgGBSqs4SZwwub5UDW1lE+SqBYtlp5PFToQziUuUeQzneOxdoup2C3DvYcWKnDOVcbk1QL95/euw9XpHbdCfHvAYqWCQVVIzrk1nAlB5ajp3CaHmY0E9UBBb4GsQAs=
  template:
    metadata:
      creationTimestamp: null
      name: redis-password-secret
      namespace: votingbooth-prod
