apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JerOdd/VotingBooth-ArgoCD
    targetRevision: HEAD
    path: envs/local 
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true