apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votingbooth-ingress
  namespace: votingbooth-local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: votingbooth.local
      http:
        paths:
          - path: /votes
            pathType: Prefix
            backend:
              service:
                name: vote-api
                port:
                  number: 80