apiVersion: v2
name: redis
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: 19.6.3
    repository: https://charts.bitnami.com/bitnami