apiVersion: v1
kind: Secret
metadata:
  name: votingbooth-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo
stringData:
  name: votingbooth-helm
  type: helm 
  url: https://jerodd.github.io/VotingBooth-Helm