apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JerOdd/VotingBooth-Helm.git
    path: .
    targetRevision: HEAD
    helm:
      values: |
        name: "vote-api"
        namespace: "votingbooth-local"
        deployment:
          image:
            repository: "vote-api"
            tag: "latest"
          imagePullPolicy: "Never"
          envs:
            REDIS_HOST: "localhost"
            REDIS_PORT: "6379"
  destination:
    server: https://kubernetes.default.svc
    namespace: votingbooth-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true