apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jerodd.github.io/VotingBooth-Helm
    targetRevision: 0.1.0
    chart: vote-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: votingbooth-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true